### ISSUE TITLE
Feature request: Lock control to force loading a particular doodle

### ISSUE THREAD

**Issue by treyturner** [fluuuid/codedoodl.es-chrome-extension#5]
Hello,
Thanks for your work on code doodles and this plugin! It would be very cool to have a lock icon/toggle at the bottom of the screen (next to reload and random) that would force loading of the current doodle on each new tab. This way, if we love a doodle, we can lock it in for a while, and when we get bored of it, we can go back to random.

Thanks for your consideration!

**Comment by silviopaganini** [comment]
interesting ! +1
