### ISSUE TITLE
Feature request: Opt out of particular doodles

### ISSUE THREAD

**Issue by treyturner** [fluuuid/codedoodl.es-chrome-extension#6]
Hi again,
This is surely lower priority since all of the doodles you guys make are sooo boss, but in some cases it would be nice to be able to disable specific doodles which aren't compatible or don't perform well on a particular system.

Thanks for your time!

**Comment by silviopaganini** [comment]
Hi there, 

how do you mean it? in the chrome extension or on the site? It would be a bit difficult to do some tests and see which machine run what since we don't have exactly all the details from the creators... 

can you elaborate a bit more?

cheers

**Comment by treyturner** [comment]
This request is for the Chrome extension. A simple implementation might be as easy as storing a comma separated list of Doodle numbers to block during random selection. A more complex implementation might poll your site to see which Doodles are published, render that list to an extension options page with checkboxes, and then let the user toggle each Doodle as blocked or enabled. All Doodles would be enabled by default, but this feature would allow users to specify any Doodles they wish to block for whatever reason they might have (preference, compatibility, performance).

You guys also have an error screen which states when the browser environment doesn't support the Doodle - a link to block that Doodle would also be useful on that error screen.

Thanks again for your work and consideration. People ask me about my new tabs all the time. =)
